version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: bonsay_nginx
    restart: always
    tty: true
    depends_on:
      - node
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/bonsay.istmen.space/fullchain.pem:/etc/letsencrypt/live/bonsay.istmen.space/fullchain.pem
      - /etc/letsencrypt/live/bonsay.istmen.space/privkey.pem:/etc/letsencrypt/live/bonsay.istmen.space/privkey.pem
      - /etc/letsencrypt/live/admin.bonsay.istmen.space-0001/fullchain.pem:/etc/letsencrypt/live/admin.bonsay.istmen.space/fullchain.pem
      - /etc/letsencrypt/live/admin.bonsay.istmen.space-0001/privkey.pem:/etc/letsencrypt/live/admin.bonsay.istmen.space/privkey.pem

    ports:
      - 80:80
      - 443:443
    networks:
      - bonsay
  node:
    build: ./
    container_name: bonsay_api
    restart: always
    tty: true
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./public/files:/app/public/files
    networks:
      - bonsay
  db:
    image: postgres:13-alpine
    container_name: bonsay_db
    restart: always
    tty: true
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'bonsay'
    volumes:
      - data:/var/lib/postgresql/data
    secrets:
      - postgres_password
    networks:
      - bonsay

volumes:
  data:
    name: bonsay_data

networks:
  bonsay:
    external: true

secrets:
  postgres_password:
    file: ./docker_postgres_password
