version: '3.8'

services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: bonsay_api
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3020:3020
    networks:
      - bonsay
  db:
    image: postgres:13-alpine
    container_name: bonsay_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'bonsay'
    volumes:
      - data:/var/lib/postgresql/bonsay_data
    networks:
      - bonsay
volumes:
  data:
    name: bonsay_data
networks:
  bonsay:
    external: true
