version: '3.8'

services:
  node:
    build: ./
    container_name: bonsay_api
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 3030:3000
      - 9229:9229
    volumes:
      - .:/app
      - /app/node_modules
  db:
    image: postgres:13
    container_name: bonsay_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'bonsay'
    volumes:
      - data:/var/lib/postgresql/bonsay_data
volumes:
  data:
    name: bonsay_data
